# Board config
BOARD_SIZE = 5

# MCTS config
MCTS_DYNAMIC_SIMS = True
MCTS_DYNAMIC_SIMS_TIME = 1
MCTS_MIN_SIMULATIONS = 1000

MTCS_SIMULATIONS = 1000
MTCS_C = 2.83
EPSILON = 1.0
EPSILON_DECAY = 0.998
EPSILON_CRITIC = 2.0
EPSILON_DECAY_CRITIC = 0.996

# RL config
NUM_EPISODES = 500
DISPLAY_GAME_RL = False
DISPLAY_GAME_RL_INTERVAL = 10
REPLAY_BUFFER_SIZE = 1000
CHECK_WINNING_MOVES_RL = True

# ANN config
NN_TYPE = "ann"
LEARNING_RATE = 0.001
NEURAL_NETWORK_DIMENSIONS = (1024, 512)
ACTIVATION_FUNCTION = "relu"
OUTPUT_ACTIVATION_FUNCTION_ACTOR = "softmax"
OUTPUT_ACTIVATION_FUNCTION_CRITIC = "tanh"
ANN_OPTIMIZER = "Adam"
LOSS_FUNCTION_ACTOR = "categorical_crossentropy"
LOSS_FUNCTION_CRITIC = "mse"
BATCH_SIZE = 128
NUM_EPOCHS = 10

# TOPP
MODEL_DIR = "models"
TOPP_TEMPERATURE = 1.0
TOPP_M = 11
TOPP_NUM_GAMES = 30
TOPP_VERBOSE = True
TOPP_DISPLAY_GAMES = True
